<a href="https://colab.research.google.com/github/harshithareddy888/PortifolioProjects/blob/main/webScrapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from bs4 import BeautifulSoup
import requests
import smtplib #this library is for sending emails to yourself
import time
import datetime

In [ ]:
# #connect to the website
# url = 'https://www.amazon.in/Bloomsbury-Mahabharata-Unravelled-Lesser-Known-Well-Known/dp/9354351271/ref=sr_1_1?dib=eyJ2IjoiMSJ9.BVEdQTrdP5L62kCkbEsfxM1U0pvYytfyLQpx0FFASFrlVe3zHQaGTSr4kT_ZdRahlTA6WcIHsuQslzzU06qssjahrI9KXYcuJ_OhlxcZatjp2iLHuSapzTN85KRmWyY8JALezBZ1v4flo0Mch56Q_w.DKrMx0Bf31bT-WgFSKiYaImF134QCh7zl7ros4SGzP4&dib_tag=se&keywords=mahabharat+book+by+ami+ganatra&qid=1756195221&sr=8-1'
# #header is user agent which is unique for every computer and we can get it from 'httpbin.org/get'
# headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"}
# page = requests.get(url, headers=headers)
# soup1 = BeautifulSoup(page.content, "html.parser")
# soup2 = BeautifulSoup(soup1.prettify(), "html.parser") #this makes the retrived html data prettier
# title = soup2.find(id='productTitle').get_text()
# print(title)

In [ ]:
#connect to the website
url = 'http://books.toscrape.com/'
# You can add headers if needed, but for this site, it's usually not required
headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"}

page = requests.get(url) # Removed headers as they are not necessary for this site
soup1 = BeautifulSoup(page.content, "html.parser")
# For this site, prettify() is not strictly necessary to find the title, but you can use it
soup2 = BeautifulSoup(soup1.prettify(), "html.parser")

# Find the title of the first book
# The book titles are within <h3> tags, inside a product_pod div
title = soup1.find('article', class_='product_pod').h3.a['title'] # Used soup1 as prettify() is optional

# Find the price of the first book
# The price is within a <p class="price_color"> tag
price = soup1.find('article', class_='product_pod').find('p', class_='price_color').get_text()
print(title)
price=price.strip()[1:]
print(price)

A Light in the Attic
51.77

In [ ]:
import datetime
today=datetime.date.today()
print(today)

2025-08-26

In [ ]:
#create a csv then import and automate the data automatically
import csv
header = ['Title', 'Price','Date']
data = [title, price,today]
# The filename needs to be in quotes
with open('scrappingData.csv','w', newline='', encoding='UTF8') as f:
    writer = csv.writer(f) #creating the csv
    writer.writerow(header) #inserting the header
    writer.writerow(data) #inserting the data

In [ ]:
import pandas as pd
# Correct the file path with a leading slash
csv_file_path = '/content/scrappingData.csv'
df = pd.read_csv(csv_file_path)
display(df)

                   Title  Price        Date
0   A Light in the Attic  51.77  2025-08-26
1   A Light in the Attic  51.77  2025-08-26
2   A Light in the Attic  51.77  2025-08-26
3   A Light in the Attic  51.77  2025-08-26
4   A Light in the Attic  51.77  2025-08-26
5   A Light in the Attic  51.77  2025-08-26
6   A Light in the Attic  51.77  2025-08-26
7   A Light in the Attic  51.77  2025-08-26
8   A Light in the Attic  51.77  2025-08-26
9   A Light in the Attic  51.77  2025-08-26
10  A Light in the Attic  51.77  2025-08-26
11  A Light in the Attic  51.77  2025-08-26
12  A Light in the Attic  51.77  2025-08-26
13  A Light in the Attic  51.77  2025-08-26
14  A Light in the Attic  51.77  2025-08-26
15  A Light in the Attic  51.77  2025-08-26

In [ ]:
#Now append the data
with open('scrappingData.csv','a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f) #creating the csv
    writer.writerow(data) #inserting the data

In [ ]:
#automating the data entry into the csv
def check_price():
  #connect to the website
  url = 'http://books.toscrape.com/'
  headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"}
  page = requests.get(url)
  soup1 = BeautifulSoup(page.content, "html.parser")
  soup2 = BeautifulSoup(soup1.prettify(), "html.parser")

  title = soup1.find('article', class_='product_pod').h3.a['title']
  price = soup1.find('article', class_='product_pod').find('p', class_='price_color').get_text()
  price=price.strip()[1:]
  import datetime
  today=datetime.date.today()
  import csv
  header = ['Title', 'Price','Date']
  data = [title, price,today]
  with open('scrappingData.csv','a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f) #creating the csv
    writer.writerow(data) #inserting the data

In [ ]:
#using time library we put it on a timer
while(True):
  check_price()
  time.sleep(5)

KeyboardInterrupt:

In [ ]:
import pandas as pd
# Correct the file path with a leading slash
csv_file_path = '/content/scrappingData.csv'
df = pd.read_csv(csv_file_path)
display(df)

                   Title  Price        Date
0   A Light in the Attic  51.77  2025-08-26
1   A Light in the Attic  51.77  2025-08-26
2   A Light in the Attic  51.77  2025-08-26
3   A Light in the Attic  51.77  2025-08-26
4   A Light in the Attic  51.77  2025-08-26
5   A Light in the Attic  51.77  2025-08-26
6   A Light in the Attic  51.77  2025-08-26
7   A Light in the Attic  51.77  2025-08-26
8   A Light in the Attic  51.77  2025-08-26
9   A Light in the Attic  51.77  2025-08-26
10  A Light in the Attic  51.77  2025-08-26
11  A Light in the Attic  51.77  2025-08-26
12  A Light in the Attic  51.77  2025-08-26
13  A Light in the Attic  51.77  2025-08-26
14  A Light in the Attic  51.77  2025-08-26
15  A Light in the Attic  51.77  2025-08-26